# POST http://localhost:4000/epione/signup
# Content-Type: application/json

# {
#     "fullname":"Veer Das",
#     "phone": "8897529922",
#     "email":"veer@hotmail.com",
#     "password": "veer123",
#     "gender":"Male",
#     "height":"186",
#     "weight": "80",
#     "bloodgroup": "O+"  
# }
GET http://localhost:4000/epione/signin
Content-Type: application/json

{
    "phone": "8897529922",
    "password": "veer123"
}